version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: miusuario/devops-app
    container_name: app
    depends_on:
      - mongodb
    ports:
      - "8080:8080"

volumes:
  mongodb_data:
